# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-1.1.1";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
  };
  "click" = super.buildPythonPackage {
    name = "click-7.0";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/5c/f60e9d8a1e77005f664b76ff8aeaee5bc05d0a91798afd7f53fc998dbc47/Click-7.0.tar.gz";
      sha256 = "1mzjixd4vjbjvzb6vylki9w1556a9qmdh35kzmq6cign46av952v";
    };
  };
  "configobj" = super.buildPythonPackage {
    name = "configobj-5.0.6";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz";
      sha256 = "00h9rcmws03xvdlfni11yb60bz3kxfvsj6dg6nrpzj71f03nbxd2";
    };
  };
  "contexter" = super.buildPythonPackage {
    name = "contexter-0.1.4";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/8e/fa97d40616c8d1bda8f83b12ab0ccf9fe0420cb89cf73184436bd3c581fe/contexter-0.1.4.tar.gz";
      sha256 = "1a50bqqbzf9hvggblmppv00pvjnx3kmdhl33990m2l4i385qjc67";
    };
  };
  "jinja2" = super.buildPythonPackage {
    name = "jinja2-2.10.1";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/ea/d884a06f8c7f9b7afbc8138b762e80479fb17aedbbe2b06515a12de9378d/Jinja2-2.10.1.tar.gz";
      sha256 = "04shqrs56aj04ipyqykj512rw2l0zfammvj9krawzxz7xc14yp06";
    };
  };
  "pip" = super.buildPythonPackage {
    name = "pip-19.2.2";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/1a/62fb0b95b1572c76dbc3cc31124a8b6866cbe9139eb7659ac7349457cf7c/pip-19.2.2.tar.gz";
      sha256 = "0lsa4908zi84cdcfzlvmsyfxj3kvb14f9is41bai1qkib2106lg0";
    };
  };
  "pip2nix" = super.buildPythonPackage {
    name = "pip2nix-0.8.0.dev1";
    buildInputs = [];
    doCheck = true;
    makeWrapperArgs = "--prefix PATH : ${pkgs.nix-prefetch-scripts}";
    propagatedBuildInputs = [
      self."click"
      self."configobj"
      self."contexter"
      self."jinja2"
      self."pip"
    ];
    src = ./.;
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    buildInputs = [];
    doCheck = false;
    propagatedBuildInputs = [];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };

### Test requirements

  py = super.buildPythonPackage {
    name = "py-1.4.32";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/93/bd/8a90834a287e0c1682eab8e20ada672e4f4cf7d5b99f2833ddbf31ed1a6d/py-1.4.32.tar.gz";
      sha256 = "19s1pql9pq85h1qzsdwgyb8a3k1qgkvh33b02m8kfqhizz8rzf64";
    };
  };
  pytest = super.buildPythonPackage {
    name = "pytest-3.0.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [py];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a8/87/b7ca49efe52d2b4169f2bfc49aa5e384173c4619ea8e635f123a0dac5b75/pytest-3.0.5.tar.gz";
      sha256 = "1z9pj39w0r2gw5hsqndlmsqa80kgbrann5kfma8ww8zhaslkl02a";
    };
  };
}
