# Generated by pip2nix 0.5.0.dev1
# See https://github.com/johbo/pip2nix

{
  args = super.buildPythonPackage {
    name = "args-0.1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e5/1c/b701b3f4bd8d3667df8342f311b3efaeab86078a840fb826bd204118cc6b/args-0.1.0.tar.gz";
      sha256 = "057qzi46h5dmxdqknsbrssn78lmqjlnm624iqdhrnpk26zcbi1d7";
    };
  };
  bumpversion = super.buildPythonPackage {
    name = "bumpversion-0.5.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/14/41/8c9da3549f8e00c84f0432c3a8cf8ed6898374714676aab91501d48760db/bumpversion-0.5.3.tar.gz";
      sha256 = "0zn7694yfipxg35ikkfh7kvgl2fissha3dnqad2c5bvsvmrwhi37";
    };
  };
  clint = super.buildPythonPackage {
    name = "clint-0.5.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [args];
    src = fetchurl {
      url = "https://pypi.python.org/packages/3d/b4/41ecb1516f1ba728f39ee7062b9dac1352d39823f513bb6f9e8aeb86e26d/clint-0.5.1.tar.gz";
      sha256 = "1an5lkkqk1zha47198p42ji3m94xmzx1a03dn7866m87n4r4q8h5";
    };
  };
  pkginfo = super.buildPythonPackage {
    name = "pkginfo-1.4.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/58/54/57f7c5638fecdf232a5b6b767da467b0ff31467d7f86a7364c252acf2321/pkginfo-1.4.1.tar.gz";
      sha256 = "17pqjfpq3c6xzdmk8pski6jcjgjv78q00zjf2bgzb668pzm6l6mv";
    };
  };
  requests = super.buildPythonPackage {
    name = "requests-2.12.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6e/40/7434b2d9fe24107ada25ec90a1fc646e97f346130a2c51aa6a2b1aba28de/requests-2.12.1.tar.gz";
      sha256 = "0bk1icw64h0502xrllv19011p5vrv3qhyja0w05ri46zjkmfq291";
    };
  };
  requests-toolbelt = super.buildPythonPackage {
    name = "requests-toolbelt-0.7.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [requests];
    src = fetchurl {
      url = "https://pypi.python.org/packages/59/78/1d391d30ebf74079a8e4de6ab66fdca5362903ef2df64496f4697e9bb626/requests-toolbelt-0.7.0.tar.gz";
      sha256 = "06n9qcpxjcj118b5lxc3q2yzwdj2ghrms4dwkxg0ygwwam59v29k";
    };
  };
  setuptools = super.buildPythonPackage {
    name = "setuptools-29.0.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6f/4f/62e4eb1ff67f8877434b3aaa62298cd0abcac9a73aee44b00249b9bac1f7/setuptools-29.0.0.zip";
      sha256 = "03amvvac464fm926w45g759pdjyvqb7p1dmc514ypa12yqk9dbh5";
    };
  };
  twine = super.buildPythonPackage {
    name = "twine-1.8.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [clint pkginfo requests requests-toolbelt setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e4/fc/735c94592f63ac511bd694019910bf484bb38c7ae874b2726d3aca82f897/twine-1.8.1.tar.gz";
      sha256 = "10nsq40v0ihkcrzspjgz7crvcs5v88nrjg45j97q8ywl39ln7dk8";
    };
  };

### Test requirements

  
}
